#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DiboAndroid.Resource", IsApplication=true)]

namespace DiboAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_backgroud = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int bt_main_background = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int bt_main_text = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int et_backgroud = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int et_border = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_home = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_lock = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_phone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_search = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_setting = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_verify = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001d
			public const int bt_verify = 2131165213;
			
			// aapt resource value: 0x7f070008
			public const int btnLogin = 2131165192;
			
			// aapt resource value: 0x7f070020
			public const int btnRegister = 2131165216;
			
			// aapt resource value: 0x7f07000e
			public const int button1 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int button2 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int button3 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int button4 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int button5 = 2131165202;
			
			// aapt resource value: 0x7f070017
			public const int button_addproject = 2131165207;
			
			// aapt resource value: 0x7f070002
			public const int editText1 = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int gridLayout1 = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int imageView1 = 2131165187;
			
			// aapt resource value: 0x7f070018
			public const int listView_project = 2131165208;
			
			// aapt resource value: 0x7f070007
			public const int login_password = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int login_phone = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int mapView = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int myButton = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int projectlogo = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int projectname = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int projectstatus = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int projectupdate = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int rg_linearLayout = 2131165209;
			
			// aapt resource value: 0x7f07001f
			public const int rg_password = 2131165215;
			
			// aapt resource value: 0x7f07001b
			public const int rg_phone = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int rg_tableRow1 = 2131165210;
			
			// aapt resource value: 0x7f07001e
			public const int rg_tableRow2 = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int rg_verify = 2131165212;
			
			// aapt resource value: 0x7f070000
			public const int tableRow1 = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int tableRow2 = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int textView5 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int tvForgetPassword = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int tvNewUser = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CreateProject = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int lgoin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ProjectBord = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int projectItem = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ProjectList = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Register = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060010
			public const int add_item = 2131099664;
			
			// aapt resource value: 0x7f060002
			public const int add_location = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int forgetpwd = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int get_verification = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int hint_phone = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int hint_pwd = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int hint_user = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int host = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int login = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int newuser = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int password = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int phone = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int register = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int username = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int verification = 2131099661;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
